#!/usr/bin/env bash
set -e

# create build if we are on main branch
staged_files=$(git diff --name-only --cached)
src_files_changed=false
for file in $staged_files; do
    if [[ $file == "src/"* ]]; then
        src_files_changed=true
        break
    fi
done
branch=$(git rev-parse --abbrev-ref HEAD)
if [[ $src_files_changed && "$branch" == "main" ]]; then
    npm run build
    git add docs
    git commit -m 'chore: build'
fi
